# Generated by Django 4.2.5 on 2023-09-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tomatoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=4)),
                ('location', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
                ('spot_size', models.CharField(max_length=10)),
                ('spot_color', models.CharField(max_length=20)),
                ('spot_dist', models.CharField(max_length=100)),
                ('leaf_texture', models.CharField(max_length=100)),
                ('overall_health', models.CharField(max_length=255)),
                ('nearby_plant_observations', models.CharField(max_length=200)),
                ('spore_fungal', models.CharField(max_length=5)),
                ('onset_time', models.CharField(max_length=5)),
                ('recent_pest_activities', models.CharField(max_length=255)),
                ('disease_history', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
